name: build-env
channels:
  - conda-forge
dependencies:
  - linkify-it-py
  - myst-parser
  - pip
  - pydata-sphinx-theme
  - sphinx-autobuild
  - pip:
    - jupyterlite-xeus-python==0.8.0
    - sphinxcontrib-video
    - voici==0.3.3
    - voila-material=0.4.3
